language: node_js
node_js:
  - "8.9.0"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
script:
  - npm run generate-import-map
  - npm run eslint-check
  - npm run prettier-check
  - npm run generate-coverage
after_success:
  - npm run upload-coverage
