name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: node 12 on ubuntu
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.0
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        run: npm run eslint-check
      - name: code format
        run: npm run prettier-check
      - name: testing
        run: npm run test-with-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload coverage
        run: npm run upload-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: auto publish
        if: github.event_name == 'push'
        run: node ./.github/auto-publish.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: auto release on github
        if: github.event_name == 'push'
        run: node ./.github/auto-release-on-github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
